project_id = "kjbamfitkaxnfyppplaq"

[functions.generate-hero]
verify_jwt = false

[functions.generate-view]
verify_jwt = false

[functions.generate-element]
verify_jwt = false

[functions.save-render-image]
verify_jwt = false

[functions.generate-materials]
verify_jwt = false

[functions.generate-3d-brief]
verify_jwt = false

[functions.generate-presentation]
verify_jwt = false