import { useState, useEffect, useRef, useMemo, useCallback } from "react";
import { useProjectStore, ELEMENT_META } from "@/store/projectStore";
import type { ElementType, ElementState } from "@/types/brief";
import { cn } from "@/lib/utils";
import {
  Play,
  Check,
  Loader2,
  AlertCircle,
  ChevronRight,
  Sparkles,
  RefreshCw
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { useProjectNavigate } from "@/hooks/useProjectNavigate";
import { supabase } from "@/integrations/supabase/client";
import { saveProjectField, ELEMENT_DB_KEYS } from "@/hooks/useProjectSync";
import { ElementDetailPanel } from "./ElementDetailPanel";
import { useKnowledgeBase } from "@/hooks/useKnowledgeBase";
import { useCompanyProfile, useShowCosts } from "@/hooks/useCompanyProfile";
import { useBrandIntelligence, useClient, useBatchCreateIntelligence } from "@/hooks/useClients";
import { IntelligenceSelector } from "./IntelligenceSelector";
import { useBrandRAG } from "@/hooks/useBrandRAG";


const ELEMENT_ORDER: ElementType[] = [
  "bigIdea",
  "experienceFramework",
  "interactiveMechanics",
  "digitalStorytelling",
  "humanConnection",
  "adjacentActivations",
  "spatialStrategy",
  "budgetLogic",
];

// ── Module-level generation tracker ──
// Survives component unmount/remount so generation continues in background
interface GenerationJob {
  projectId: string;
  promise: Promise<void>;
  aborted: boolean;
  completedElements: Set<ElementType>;
  failedElements: Set<ElementType>;
}

let activeJob: GenerationJob | null = null;

function getActiveJob(projectId: string): GenerationJob | null {
  if (activeJob && activeJob.projectId === projectId && !activeJob.aborted) {
    return activeJob;
  }
  return null;
}

async function runGenerationJob(
  projectId: string,
  elementsToGenerate: ElementType[],
  briefData: any,
  existingElements: Record<ElementType, ElementState>,
  knowledgeBaseContent: any[] | undefined,
  companyProfile: any | undefined,
  showCosts: any[] | undefined,
  isRegenerate: boolean,
  brandIntelligence?: any[],
  clientData?: any,
  projectType?: string,
  brandContext?: string,
  suiteContext?: string,
): Promise<GenerationJob> {
  // Abort any existing job
  if (activeJob) {
    activeJob.aborted = true;
  }

  const job: GenerationJob = {
    projectId,
    promise: Promise.resolve(),
    aborted: false,
    completedElements: new Set(),
    failedElements: new Set(),
  };
  activeJob = job;

  job.promise = (async () => {
    for (const elementType of elementsToGenerate) {
      if (job.aborted) break;

      // Update store status to generating
      useProjectStore.getState().setElementStatus(elementType, "generating");

      try {
        const existingData = isRegenerate ? existingElements[elementType]?.data : undefined;

        const { data, error } = await supabase.functions.invoke("generate-element", {
          body: {
            elementType,
            briefData,
            existingData,
            knowledgeBaseContent: knowledgeBaseContent && knowledgeBaseContent.length > 0 ? knowledgeBaseContent : undefined,
            companyProfile,
            showCosts: showCosts && showCosts.length > 0 ? showCosts : undefined,
            brandIntelligence: brandIntelligence && brandIntelligence.length > 0 ? brandIntelligence : undefined,
            clientData,
            projectType,
            brandContext: brandContext || undefined,
            suiteContext: suiteContext || undefined,
          },
        });

        if (job.aborted) break;
        if (error) throw error;
        if (data?.error) throw new Error(data.error);

        // Save to store
        useProjectStore.getState().setElementData(elementType, data.data);
        // Persist to DB immediately so navigation doesn't lose progress
        const dbKey = ELEMENT_DB_KEYS[elementType];
        await saveProjectField(projectId, dbKey, data.data);

        job.completedElements.add(elementType);
      } catch (e: any) {
        console.error(`Error generating ${elementType}:`, e);
        if (!job.aborted) {
          useProjectStore.getState().setElementStatus(elementType, "error");
          job.failedElements.add(elementType);
        }
      }
    }
  })();

  return job;
}

export function ElementDashboard({ projectId }: { projectId: string | null }) {
  const { currentProject, setElementStatus, setElementData, setActiveStep } = useProjectStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeElement, setActiveElement] = useState<ElementType | null>(null);
  const [regeneratingElement, setRegeneratingElement] = useState<ElementType | null>(null);
  const hasAutoGenerated = useRef(false);
  const { navigate } = useProjectNavigate();
  const { toast } = useToast();
  const { files: kbFiles } = useKnowledgeBase(projectId);
  const { profile: companyProfile } = useCompanyProfile();
  const { costs: showCosts } = useShowCosts();

  // Brand intelligence + client context for AI generation
  const clientId = currentProject?.clientId ?? null;
  const parentId = currentProject?.hierarchy?.parentId ?? null;
  const { data: brandIntelEntries } = useBrandIntelligence(clientId);
  const { data: clientRecord } = useClient(clientId);
  const batchCreateIntelligence = useBatchCreateIntelligence();

  // RAG context + suite context
  const showName = currentProject?.parsedBrief?.events?.primaryShow ?? undefined;
  const { brandContext: ragBrandContext, suiteContext: ragSuiteContext } = useBrandRAG({
    clientId,
    projectId,
    parentId,
    showName,
  });

  // Approved entries for IntelligenceSelector
  const approvedEntries = useMemo(
    () => brandIntelEntries?.filter(e => e.is_approved) ?? [],
    [brandIntelEntries]
  );

  // Track which intelligence entries are selected for this generation run
  const [selectedIntelIds, setSelectedIntelIds] = useState<Set<string>>(new Set());

  // Initialize selection when entries load
  useEffect(() => {
    if (approvedEntries.length > 0 && selectedIntelIds.size === 0) {
      setSelectedIntelIds(new Set(approvedEntries.map(e => e.id)));
    }
  }, [approvedEntries]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleToggleIntel = useCallback((id: string) => {
    setSelectedIntelIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const handleToggleAllIntel = useCallback((enabled: boolean) => {
    setSelectedIntelIds(
      enabled ? new Set(approvedEntries.map(e => e.id)) : new Set()
    );
  }, [approvedEntries]);

  const elements = currentProject?.elements;
  const completedCount = elements ? ELEMENT_ORDER.filter(
    (type) => elements[type].status === "complete"
  ).length : 0;

  // Track whether a background job is running for this project
  useEffect(() => {
    if (projectId) {
      const job = getActiveJob(projectId);
      if (job) {
        setIsGenerating(true);
        job.promise.then(() => {
          if (!job.aborted) {
            setIsGenerating(false);
            toast({
              title: "All elements generated",
              description: "Click any element to review and edit the details.",
            });
          }
        });
      }
    }
  }, [projectId, toast]);

  // Reset auto-generate flag when project changes
  useEffect(() => {
    hasAutoGenerated.current = false;
  }, [projectId]);

  // Auto-generate all elements when arriving with none completed
  useEffect(() => {
    if (!hasAutoGenerated.current && currentProject?.parsedBrief && currentProject.id === projectId) {
      const noneComplete = ELEMENT_ORDER.every(
        (type) => currentProject.elements[type].status === "pending"
      );
      // Don't auto-generate if there's already an active job
      if (noneComplete && !getActiveJob(projectId!)) {
        hasAutoGenerated.current = true;
        setTimeout(() => generateAllElements(false), 300);
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentProject?.id]);

  if (!currentProject?.parsedBrief) {
    return (
      <div className="text-center py-12">
        <p className="text-muted-foreground">No brief data available</p>
        <Button variant="outline" className="mt-4" onClick={() => navigate("/upload")}>
          Upload a Brief
        </Button>
      </div>
    );
  }

  const getContextPayloads = () => {
    const knowledgeBaseContent = kbFiles
      .filter(f => f.extracted_text)
      .map(f => ({ fileName: f.file_name, content: f.extracted_text! }));

    const cpPayload = companyProfile ? {
      companyName: companyProfile.company_name,
      industry: companyProfile.industry,
      defaultBoothSizes: companyProfile.default_booth_sizes,
      notes: companyProfile.notes,
    } : undefined;

    const scPayload = showCosts.length > 0 ? showCosts.map(c => ({
      showName: c.show_name,
      city: c.city,
      venue: c.venue,
      boothCostPerSqft: c.estimated_booth_cost_per_sqft,
      drayagePerCwt: c.estimated_drayage_per_cwt,
      laborRatePerHr: c.estimated_labor_rate_per_hr,
      electricalPerOutlet: c.estimated_electrical_per_outlet,
      internetCost: c.estimated_internet_cost,
      unionRequired: c.union_labor_required,
    })) : undefined;

    // Brand intelligence: only send approved + user-selected entries
    const biPayload = approvedEntries
      .filter(e => selectedIntelIds.has(e.id))
      .map(e => ({ category: e.category, title: e.title, content: e.content, tags: e.tags }));

    // Client context
    const clientPayload = clientRecord ? {
      name: clientRecord.name,
      industry: clientRecord.industry,
      description: clientRecord.description,
      primaryColor: clientRecord.primary_color,
      secondaryColor: clientRecord.secondary_color,
      website: clientRecord.website,
    } : undefined;

    // Project type
    const projectTypeId = currentProject?.projectType ?? undefined;

    return { knowledgeBaseContent, cpPayload, scPayload, biPayload, clientPayload, projectTypeId, ragBrandContext, ragSuiteContext };
  };

  const generateElement = async (elementType: ElementType, feedback?: string) => {
    setElementStatus(elementType, "generating");

    try {
      const { knowledgeBaseContent, cpPayload, scPayload, biPayload, clientPayload, projectTypeId, ragBrandContext: bc, ragSuiteContext: sc } = getContextPayloads();

      const { data, error } = await supabase.functions.invoke("generate-element", {
        body: {
          elementType,
          briefData: currentProject.parsedBrief,
          existingData: feedback ? elements![elementType].data : undefined,
          feedback,
          knowledgeBaseContent: knowledgeBaseContent.length > 0 ? knowledgeBaseContent : undefined,
          companyProfile: cpPayload,
          showCosts: scPayload,
          brandIntelligence: biPayload && biPayload.length > 0 ? biPayload : undefined,
          clientData: clientPayload,
          projectType: projectTypeId,
          brandContext: bc || undefined,
          suiteContext: sc || undefined,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setElementData(elementType, data.data);
      if (projectId) {
        const dbKey = ELEMENT_DB_KEYS[elementType];
        await saveProjectField(projectId, dbKey, data.data);
      }
      toast({ title: `${ELEMENT_META[elementType].title} generated` });
    } catch (e: any) {
      console.error(`Error generating ${elementType}:`, e);
      setElementStatus(elementType, "error");
      toast({
        title: "Generation failed",
        description: e.message || "Please try again.",
        variant: "destructive",
      });
    }
  };

  const generateAllElements = async (isRegenerate: boolean) => {
    if (!projectId || !currentProject?.parsedBrief) return;

    setIsGenerating(true);

    const { knowledgeBaseContent, cpPayload, scPayload, biPayload, clientPayload, projectTypeId, ragBrandContext: bc, ragSuiteContext: sc } = getContextPayloads();

    const job = await runGenerationJob(
      projectId,
      ELEMENT_ORDER,
      currentProject.parsedBrief,
      currentProject.elements,
      knowledgeBaseContent,
      cpPayload,
      scPayload,
      isRegenerate,
      biPayload && biPayload.length > 0 ? biPayload : undefined,
      clientPayload,
      projectTypeId,
      bc || undefined,
      sc || undefined,
    );

    // Wait for completion (component may unmount, that's fine — job continues)
    await job.promise;

    if (!job.aborted) {
      setIsGenerating(false);
      toast({
        title: "All elements generated",
        description: "Click any element to review and edit the details.",
      });
    }
  };

  const handleRegenerateFromDetail = async (elementType: ElementType, feedback?: string) => {
    setRegeneratingElement(elementType);
    await generateElement(elementType, feedback);
    setRegeneratingElement(null);

    // Phase 1E: Auto-capture feedback as brand intelligence (past_learning)
    if (feedback && feedback.trim().length > 0 && clientId && projectId) {
      const elementLabel = ELEMENT_META[elementType]?.title ?? elementType;
      batchCreateIntelligence.mutate([
        {
          client_id: clientId,
          category: "past_learning" as const,
          title: `Feedback on ${elementLabel}`,
          content: feedback.trim(),
          tags: [elementType, "regen_feedback"],
          source: "feedback" as const,
          confidence_score: null,
          source_project_id: projectId,
          is_approved: true,
          approved_at: new Date().toISOString(),
        },
      ]);
    }
  };

  const handleUpdateField = (elementType: ElementType, path: string, value: any) => {
    const data = { ...elements![elementType].data };
    const keys = path.split(".");
    let obj = data;
    for (let i = 0; i < keys.length - 1; i++) {
      const key = keys[i];
      if (Array.isArray(obj[key])) {
        obj[key] = [...obj[key]];
        obj = obj[key];
      } else {
        obj[key] = { ...obj[key] };
        obj = obj[key];
      }
    }
    obj[keys[keys.length - 1]] = value;
    setElementData(elementType, data);
  };

  const handleContinue = () => {
    setActiveStep("spatial");
    navigate(projectId ? `/spatial?project=${projectId}` : "/spatial");
  };

  if (activeElement) {
    const element = elements![activeElement];
    return (
      <ElementDetailPanel
        elementType={activeElement}
        data={element.data}
        onBack={() => setActiveElement(null)}
        onRegenerate={(feedback) => handleRegenerateFromDetail(activeElement, feedback)}
        onUpdateField={(path, value) => handleUpdateField(activeElement, path, value)}
        isRegenerating={regeneratingElement === activeElement}
      />
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold">Strategic Elements</h2>
          <p className="text-muted-foreground">
            {completedCount} of {ELEMENT_ORDER.length} elements ready — click any to expand
          </p>
        </div>
        <div className="flex gap-3">
          <Button
            onClick={() => generateAllElements(completedCount > 0)}
            disabled={isGenerating}
            className="btn-glow"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating with AI...
              </>
            ) : completedCount === ELEMENT_ORDER.length ? (
              <>
                <RefreshCw className="mr-2 h-4 w-4" />
                Regenerate All
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                Generate All with AI
              </>
            )}
          </Button>
          {completedCount === ELEMENT_ORDER.length && (
            <Button onClick={handleContinue} variant="outline">
              Continue to Spatial
              <ChevronRight className="ml-2 h-4 w-4" />
            </Button>
          )}
        </div>
      </div>

      {/* Brand Intelligence Selector */}
      {approvedEntries.length > 0 && (
        <IntelligenceSelector
          entries={approvedEntries}
          selectedIds={selectedIntelIds}
          onToggle={handleToggleIntel}
          onToggleAll={handleToggleAllIntel}
        />
      )}

      {/* Progress Bar */}
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div 
          className="h-full bg-primary transition-all duration-500"
          style={{ width: `${(completedCount / ELEMENT_ORDER.length) * 100}%` }}
        />
      </div>

      {/* Elements Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {ELEMENT_ORDER.map((elementType) => {
          const element = elements![elementType];
          const meta = ELEMENT_META[elementType];
          
          return (
            <ElementCard
              key={elementType}
              element={element}
              meta={meta}
              onClick={() => {
                if (element.status === "complete") {
                  setActiveElement(elementType);
                }
              }}
              onGenerate={() => generateElement(elementType)}
              isGenerating={element.status === "generating"}
            />
          );
        })}
      </div>
    </div>
  );
}

interface ElementCardProps {
  element: ElementState;
  meta: typeof ELEMENT_META[ElementType];
  onClick: () => void;
  onGenerate: () => void;
  isGenerating: boolean;
}

function ElementCard({ element, meta, onClick, onGenerate, isGenerating }: ElementCardProps) {
  const statusStyles = {
    pending: "bg-muted text-muted-foreground",
    generating: "bg-primary/10 text-primary",
    complete: "bg-status-complete/10 text-status-complete",
    error: "bg-destructive/10 text-destructive",
  };

  const statusIcons = {
    pending: null,
    generating: <Loader2 className="h-3 w-3 animate-spin" />,
    complete: <Check className="h-3 w-3" />,
    error: <AlertCircle className="h-3 w-3" />,
  };

  return (
    <Card 
      className={cn(
        "element-card transition-all",
        element.status === "complete" && "active cursor-pointer",
        element.status === "complete" && "hover:scale-[1.02]"
      )}
      onClick={element.status === "complete" ? onClick : undefined}
    >
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between">
          <span className="text-2xl">{meta.icon}</span>
          <Badge 
            variant="secondary" 
            className={cn("text-xs", statusStyles[element.status])}
          >
            {statusIcons[element.status]}
            <span className="ml-1 capitalize">{element.status}</span>
          </Badge>
        </div>
        <CardTitle className="text-sm font-medium">{meta.title}</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-xs text-muted-foreground mb-3">
          {meta.description}
        </p>
        
        {element.status === "complete" && element.data && (
          <div className="text-xs text-foreground/80 mb-3 line-clamp-3">
            {getPreviewText(element)}
          </div>
        )}

        {element.status === "complete" ? (
          <div className="flex items-center gap-1 text-xs text-primary font-medium">
            <span>Click to expand</span>
            <ChevronRight className="h-3 w-3" />
          </div>
        ) : (
          <Button
            variant="ghost"
            size="sm"
            onClick={(e) => { e.stopPropagation(); onGenerate(); }}
            disabled={isGenerating}
            className="w-full text-xs"
          >
            {element.status === "generating" ? (
              <>
                <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                Generating...
              </>
            ) : element.status === "error" ? (
              <>
                <RefreshCw className="mr-1 h-3 w-3" />
                Retry
              </>
            ) : (
              <>
                <Play className="mr-1 h-3 w-3" />
                Generate
              </>
            )}
          </Button>
        )}
      </CardContent>
    </Card>
  );
}

function getPreviewText(element: ElementState): string {
  const data = element.data;
  if (!data) return "";
  
  switch (element.type) {
    case "bigIdea":
      return data.headline || "";
    case "experienceFramework":
      return data.conceptDescription?.slice(0, 120) + "..." || "";
    case "interactiveMechanics":
      return data.hero?.name ? `${data.hero.name} — ${data.hero.concept?.slice(0, 80)}...` : "";
    case "digitalStorytelling":
      return data.philosophy?.slice(0, 120) + "..." || "";
    case "humanConnection":
      return data.scalingNotes?.slice(0, 120) + "..." || "";
    case "adjacentActivations":
      return data.competitivePositioning?.slice(0, 120) + "..." || "";
    case "spatialStrategy":
      return data.scalingStrategy?.conceptIntegrity || "";
    case "budgetLogic":
      return `$${data.totalPerShow?.toLocaleString() || ""}`;
    default:
      return "";
  }
}
