REVOKE EXECUTE ON FUNCTION public.is_super_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_agency_member(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_agency_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public._require_super_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.agency_has_access(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.agency_effective_status(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public._agency_snapshot(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public._log_agency_access(uuid, text, text, jsonb, jsonb, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.suspend_agency(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reactivate_agency(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.disable_agency(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_agency_trial(uuid, timestamptz) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_agency_feature_flags(uuid, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_agency_quotas(uuid, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_agency_admin_notes(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.list_agencies_for_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_agency_access_log(uuid, int) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_agency_member(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_agency_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.agency_has_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.agency_effective_status(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.suspend_agency(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reactivate_agency(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.disable_agency(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_agency_trial(uuid, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_agency_feature_flags(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_agency_quotas(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_agency_admin_notes(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_agencies_for_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_agency_access_log(uuid, int) TO authenticated;